### ISSUE TITLE
"HTTP ERROR 500" with OpenRefine

### ISSUE THREAD

**Issue by hauschke** [fadmaa/grefine-rdf-extension#91]
```
  HTTP ERROR 500

  Problem accessing /. Reason:

 Butterfly Error
 Butterfly incurred in the following errors while initializing:
  java.lang.Exception: Failed to initialize module rdf-extension        edu.mit.simile.butterfly.ButterflyModuleImpl]
    at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:478)
at edu.mit.simile.butterfly.Butterfly.configure(Butterfly.java:451)
at edu.mit.simile.butterfly.Butterfly.init(Butterfly.java:308)
at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
at com.google.refine.RefineServer.configure(Refine.java:293)
at com.google.refine.RefineServer.init(Refine.java:207)
at com.google.refine.Refine.init(Refine.java:114)
at com.google.refine.Refine.main(Refine.java:108)
  Caused by: org.mozilla.javascript.EvaluatorException: Can't find method   com.google.refine.RefineServlet.cacheClass(object). (file:/C:/XXXX/openrefine-2.6-beta.1/webapp/extensions/grefine-rdf-extension-0.9.0/module/MOD-INF/controller.js#82)
at  org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:109)
at org.mozilla.javascript.Context.reportRuntimeError(Context.java:938)
at org.mozilla.javascript.Context.reportRuntimeError(Context.java:994)
at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:957)
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:166)
at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
at org.mozilla.javascript.gen.c2._c4(file:/C:/XXXX/openrefine-2.6-beta.1/webapp/extensions/grefine-rdf-extension-0.9.0/module/MOD-INF/controller.js:82)
at org.mozilla.javascript.gen.c2.call(file:/C:/XXXX/openrefine-2.6-beta.1/webapp/extensions/grefine-rdf-extension-0.9.0/module/MOD-INF/controller.js)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
at org.mozilla.javascript.gen.c2.call(file:/C:/XXXX/openrefine-2.6-beta.1/webapp/extensions/grefine-rdf-extension-0.9.0/module/MOD-INF/controller.js)
at edu.mit.simile.butterfly.ButterflyModuleImpl.scriptInit(ButterflyModuleImpl.java:636)
at edu.mit.simile.butterfly.ButterflyModuleImpl.init(ButterflyModuleImpl.java:94)
at edu.mit.simile.butterfly.Butterfly.initializeModule(Butterfly.java:476)
... 8 more

 Powered by Jetty://
```

I tried the new alpha for OpenRefine, but I couldn't start OpenRefine after that.

**Comment by boriel** [comment]
Me too. :( Cannot launch. Is this project still alive??

**Comment by Liuyan661** [comment]
Have you solved this problem?

**Comment by hauschke** [comment]
I'm using the latest OpenRefine and I didn't encounter this issue lately. I haven't solved it, but it is no longer a problem for me. Please decide, if that means it can be closed or not.

**Comment by Liuyan661** [comment]
I’m using OpenRefine3.1.Can you tell me the version of your OpenRefine?
发送自 Windows 10 版邮件应用

发件人: hauschke
发送时间: 2019年4月2日 16:47
收件人: fadmaa/grefine-rdf-extension
抄送: Liuyan661; Comment
主题: Re: [fadmaa/grefine-rdf-extension] "HTTP ERROR 500" with OpenRefine(#91)

I'm using the latest OpenRefine and I didn't encounter this issue lately. I haven't solved it, but it is no longer a problem for me. Please decide, if that means it can be closed or not.
